[allpush: 'missing' status]
Add the 'missing' status message.

diff --git a/git-allpush b/git-allpush
--- a/git-allpush
+++ b/git-allpush
@@ -23,12 +23,18 @@ do
 	do
 		echo -ne "\t${path} ${remote} "
 
-		git push ${remote} 1>&2 2>/dev/null
+		exists=$(git remote show | grep ${remote})
 
-		if [ $? -eq 0 ];then
-			echo -e "\033[32mok\033[0m"
+		if [ "${exists}" != "" ];then
+			git push ${remote} 1>&2 2>/dev/null
+
+			if [ $? -eq 0 ];then
+				echo -e "\033[32mok\033[0m"
+			else
+				echo -e "\033[31merror\033[0m"
+			fi
 		else
-			echo -e "\033[31merror\033[0m"
+			echo -e "\033[33mmissing\033[0m"
 		fi
 	done
 
